model_list: 
  - model_name: meta-llama/Meta-Llama-3.1-8B-Instruct
    litellm_params:
      model: openai/meta-llama/Meta-Llama-3.1-8B-Instruct
      api_base: http://localhost:8000/v1
      api_key: none
  - model_name: meta-llama/Meta-Llama-3.1-8B-Instruct
    litellm_params:
      model: openai/meta-llama/Meta-Llama-3.1-8B-Instruct
      api_base: http://localhost:8001/v1 
      api_key: none
  - model_name: meta-llama/Meta-Llama-3.1-8B-Instruct
    litellm_params:
      model: openai/meta-llama/Meta-Llama-3.1-8B-Instruct
      api_base: http://localhost:8002/v1
      api_key: none

litellm_settings:
  request_timeout: 600.0
  num_retries: 10
